'use client';

import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { useRouter } from 'next/navigation';
import { User, Mail, Shield, LogOut, Trash2, Download, Loader2 } from 'lucide-react';

// --- TYPES ---
interface UserProfile {
  name: string;
  email: string;
  rollNumber: string;
  program: string;
  currentCGPA: number;
  totalCredits: number;
  semestersLogged: number;
}

// --- ANIMATION WRAPPER ---
const MotionDiv = motion.div as any;

export default function ProfilePage() {
  const router = useRouter();
  const [user, setUser] = useState<UserProfile | null>(null);
  const [loading, setLoading] = useState(true);

  // 1. Fetch Real Data
  useEffect(() => {
    const fetchProfile = async () => {
      try {
        const res = await fetch('/api/user/profile');
        if (res.ok) {
          const data = await res.json();
          setUser(data);
        } else {
          // If unauthorized, redirect to login
          router.push('/login');
        }
      } catch (error) {
        console.error("Failed to load profile", error);
      } finally {
        setLoading(false);
      }
    };
    fetchProfile();
  }, [router]);

  // 2. Real Logout Logic
  const handleLogout = async () => {
    try {
      await fetch('/api/auth/logout', { method: 'POST' });
      router.push('/login');
    } catch (error) {
      console.error("Logout failed", error);
    }
  };

  const handleExportData = () => {
    if (!user) return;
    const dataToExport = {
      profile: user,
      exportDate: new Date().toISOString(),
      appVersion: "1.0-RC1",
      note: "Generated by Kaizen Academic System"
    };

    const blob = new Blob([JSON.stringify(dataToExport, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `kaizen_data_${user.name.replace(/\s+/g, '_').toLowerCase()}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (loading) {
     return (
        <div className="flex h-[80vh] items-center justify-center">
            <Loader2 className="text-primary animate-spin" size={40} />
        </div>
     );
  }

  if (!user) return null;

  return (
    <div className="max-w-3xl mx-auto pt-8 pb-20 px-4">
      
      {/* Header */}
      <div className="mb-8">
        <h2 className="text-3xl font-display font-medium mb-2 text-foreground">
          STUDENT <span className="text-primary">PROFILE</span>
        </h2>
        <p className="text-muted-foreground">Manage your identity and academic footprint.</p>
      </div>

      {/* Identity Card */}
      <MotionDiv 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-card border border-border p-8 mb-8 flex flex-col md:flex-row items-start md:items-center gap-6"
      >
        <div className="w-20 h-20 bg-accent rounded-full flex items-center justify-center border border-input text-muted-foreground">
          <User size={32} />
        </div>
        <div className="flex-1">
          <h3 className="text-2xl font-display text-foreground">{user.name}</h3>
          <div className="flex items-center gap-2 text-muted-foreground font-mono text-sm mt-1">
            <Mail size={14} />
            {user.email}
          </div>
          <div className="text-xs text-muted-foreground mt-2 font-mono">
             {user.program} • {user.rollNumber}
          </div>
        </div>
        <div className="px-4 py-2 bg-primary/10 border border-primary/20 rounded text-primary text-xs font-mono uppercase tracking-widest">
          Student ID: ACTIVE
        </div>
      </MotionDiv>

      {/* Academic Summary */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-12">
        <SummaryCard label="Total Credits" value={user.totalCredits} delay={0.1} />
        <SummaryCard label="Semesters Logged" value={user.semestersLogged} delay={0.2} />
        <SummaryCard label="Current CGPA" value={user.currentCGPA} isHighlight delay={0.3} />
      </div>

      {/* Privacy Note */}
      <MotionDiv 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.4 }}
        className="mb-12"
      >
        <h4 className="text-xs uppercase tracking-widest text-muted-foreground mb-4 flex items-center gap-2">
          <Shield size={14} /> Data Privacy Protocol
        </h4>
        <div className="p-6 bg-muted border border-border text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">
            KAIZEN operates on a secure cloud infrastructure. Your academic data (SGR PDFs, grades) is processed securely and stored in an encrypted database. You retain full ownership of your data.
          </p>
          <div className="flex items-center gap-4 mt-6">
             <motion.button 
               onClick={handleExportData}
               whileHover={{ scale: 1.02, color: "#ccff00", borderColor: "#ccff00" }}
               whileTap={{ scale: 0.98 }}
               className="flex items-center gap-2 px-4 py-2 bg-muted text-foreground border border-input transition-colors text-xs font-bold uppercase tracking-widest"
             >
               <Download size={14} /> Export JSON Data
             </motion.button>
             <span className="text-[10px] text-muted-foreground">Download a backup of your profile data.</span>
          </div>
        </div>
      </MotionDiv>

      {/* Actions */}
      <MotionDiv 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.5 }}
        className="border-t border-border pt-8 flex flex-col gap-4"
      >
        <motion.button 
          onClick={handleLogout}
          whileHover={{ backgroundColor: "#111", color: "#fff" }}
          className="flex items-center justify-center gap-2 w-full p-4 border border-input text-[#ccc] bg-transparent transition-colors uppercase tracking-widest text-xs font-bold"
        >
          <LogOut size={16} /> Secure Logout
        </motion.button>
        
        <motion.button 
          onClick={() => {
             // In a real app, this would call a DELETE API
             if(confirm('This feature is disabled for safety in this demo.')) {
                 // handleDeleteAccount();
             }
          }}
          whileHover={{ backgroundColor: "rgba(127, 29, 29, 0.1)", color: "#ef4444" }}
          className="flex items-center justify-center gap-2 w-full p-4 border border-red-900/30 text-red-500/80 bg-transparent transition-colors uppercase tracking-widest text-xs font-bold"
        >
          <Trash2 size={16} /> Delete Account Data
        </motion.button>
      </MotionDiv>
    </div>
  );
}

// --- SUB-COMPONENT ---
const SummaryCard = ({ label, value, isHighlight = false, delay = 0 }: any) => {
    return (
        <MotionDiv 
           initial={{ opacity: 0, scale: 0.9 }}
           animate={{ opacity: 1, scale: 1 }}
           transition={{ delay }}
           className={`p-6 border ${isHighlight ? 'border-primary/30 bg-primary/5' : 'border-border bg-card'}`}
        >
            <div className="text-3xl font-display font-bold text-foreground mb-1">{value}</div>
            <div className={`text-[10px] uppercase tracking-widest ${isHighlight ? 'text-primary' : 'text-muted-foreground'}`}>{label}</div>
        </MotionDiv>
    );
};