const rawText = `MONECSc1XAD LABAD LABPE-III (GrA)EECOXXPE-III (GrB)X / SWE ECSc2XVLSID LABVLSID LABPE-III (GrA)VLSIC&SEECOXPE-III (GrB)X ECSc3XCNEECOPE-III (GrA)SWEXXPE-III (GrB)X ECSc4XSWECNPE-III (GrA)EECOXXPE-III (GrB)VLSID LAB ECSc5XXXPE-III (GrA)VLSIC&SXXPE-III (GrB)CN LAB ECSc6ECSc1XXEECOEECOCNCNPE-III (GrA)PE-III (GrA)VLSIC&SVLSID LABXVLSID LABXXPE-III (GrB)SWEAD LAB VLSIC&SAD LAB X TUEECSc2XXEECOPE-III (GrA)CN LABCN LABXSWEX / CN ECSc3XXCNPE-III (GrA)AD LABAD LABXSWEVLSIC&S / X ECSc4XCNSWEPE-III (GrA)VLSIC&SXXAD LABAD LAB / X ECSc5XSWECNPE-III (GrA)VLSIC&SXXVLSID LABVLSID LAB / X ECSc6XAD LABAD LABPE-III (GrA)SWEXXEECOCN / X WEDECSc1XXCNVLSIC&SSWEXXXMINOR/OE (16:30-18:00) ECSc2XAD LABAD LABEECOVLSIC&SSWEXXMINOR/OE (16:30-18:00) ECSc3XCN LABCN LABEECOCNXXXMINOR/OE (16:30-18:00) ECSc4XSWEEECOAD LABAD LABXXXMINOR/OE (16:30-18:00) ECSc5XEECOEECOSWECNVLSIC&SXXMINOR/OE (16:30-18:00) ECSc6XXSWEVLSID LABVLSID LABXXXMINOR/OE (16:30-18:00) THUECSc1XAD LABAD LABEECOSWEPE-III (GrB)XPE-III (GrA)VLSIC&S / X ECSc2XCNSWEVLSIC&SPE-III (GrB)XPE-III (GrA)XX ECSc3XEECOVLSIC&SAD LABAD LABPE-III (GrB)XPE-III (GrA)SWE / X ECSc4XCN LABCN LABSWEVLSIC&SPE-III (GrB)XPE-III (GrA)X ECSc5ECSc6XXXSWESWEVLSIC&SCNCN LABXCN LABPE-III (GrB)PE-III (GrB)XXPE-III (GrA)PE-III (GrA)AD LAB CNAD LAB X FRIECSc1XXCNCN LABCN LABPE-III (GrB)XXMINOR/OE (16:30-18:00) ECSc2XSWECNAD LABAD LABPE-III (GrB)XXMINOR/OE (16:30-18:00) ECSc3XVLSID LABVLSID LABVLSIC&SSWEPE-III (GrB)XXMINOR/OE (16:30-18:00) ECSc4XXEECOVLSIC&SCNPE-III (GrB)XXMINOR/OE (16:30-18:00) ECSc5ECSc6XXAD LABXAD LABVLSIC&SEECOSWESWEEECOPE-III (GrB)PE-III (GrB)XXXXMINOR/OE (16:30-18:00)`;

// Normalize some slashes or variations
const cleanText = rawText.replace(/X \/ SWE|X \/ CN|VLSIC&S \/ X|AD LAB \/ X|VLSID LAB \/ X|CN \/ X|SWE \/ X/g, 'X');

// Extract tokens based on known subject names
const regex = /(AD LAB|VLSID LAB|CN LAB|SWE|VLSIC&S|CN|EECO|PE-III\s*\(GrA\)|PE-III\s*\(GrB\)|MINOR\/OE\s*\(16:30-18:00\)|X)/g;

const matches = cleanText.match(regex);
console.log(`Found ${matches ? matches.length : 0} tokens.`);
if (matches && matches.length !== 270) {
  console.log("Not exactly 270 tokens. Let's see what is missing or overcounted.");
}
console.log(matches?.slice(0, 10));
